### ISSUE TITLE
Multiline template strings are broken

### ISSUE THREAD

**Issue by Cloudy71** [roblox-ts/roblox-ts#2705] opened 2024-06-09 19:12 UTC
Hello, we've been testing our game and found out in Roblox output an error `Malformed interpolated string`.
Looks like transpiller wrongly translates it into LUA code. In previous version it was fully functional (from the TS side).
Workaround is just making it as two concatted template strings.
![image](https://github.com/roblox-ts/roblox-ts/assets/16520595/7aab6ed2-69a2-4b38-a18b-2a4988ee370a)
![image](https://github.com/roblox-ts/roblox-ts/assets/16520595/3a0efc7e-c2fb-423a-98ee-f05b496ceeeb)

**Comment by Dionysusnu** [comment] 2024-06-10 14:19
Duplicate of roblox-ts/luau-ast#458

**Comment by osyrisrblx** [comment] 2024-06-10 20:15
Closed as duplicate

**Closed by osyrisrblx** 2024-06-10 20:15 UTC
