### ISSUE TITLE
Assertion failed @ setupProjectWatchProgram.js:162

### ISSUE THREAD

**Issue by Firere** [roblox-ts/roblox-ts#2252] opened 2023-01-12 23:06 UTC
Trying to run `npx rbxtsc -w`, I get this error:
```
[22:55:18] Starting compilation in watch mode...

<project_dir>\node_modules\roblox-ts\out\Project\functions\setupProjectWatchProgram.js:162
                throw e;
                ^

Error: Assertion Failed! 
This is a compiler bug! Please submit a bug report here:
https://github.com/roblox-ts/roblox-ts/issues
    at assert (<project_dir>\node_modules\roblox-ts\out\Shared\util\assert.js:7:15)
    at createJsxAddChild (<project_dir>\node_modules\roblox-ts\out\TSTransformer\nodes\jsx\transformJsxChildren.js:159:25)
    at transformJsxChildren (<project_dir>\node_modules\roblox-ts\out\TSTransformer\nodes\jsx\transformJsxChildren.js:234:38)
    at transformJsx (<project_dir>\node_modules\roblox-ts\out\TSTransformer\nodes\jsx\transformJsx.js:31:53)
    at transformJsxElement (<project_dir>\node_modules\roblox-ts\out\TSTransformer\nodes\expressions\transformJsxElement.js:6:44)
    at transformExpression (<project_dir>\node_modules\roblox-ts\out\TSTransformer\nodes\expressions\transformExpression.js:97:16)
    at <project_dir>\node_modules\roblox-ts\out\TSTransformer\nodes\jsx\transformJsxChildren.js:243:109
    at <project_dir>\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:132:60
    at TransformState.capturePrereqs (<project_dir>\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:127:9)
    at TransformState.capture (<project_dir>\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:132:30)   

Node.js v19.3.0
```
so I'm doing as it says. Note: I do use my own versions of Roact and Hooks, but even when I use the `@rbxts/` versions of them the error is the same, and I don't use any logic not already compatible with plain roblox-ts.

**Comment by Dionysusnu** [comment] 2023-01-13 09:33
Probably duplicate of #2139, #2084. Check that all your JSX child expressions are valid Roact components.

**Closed** 2023-01-14 20:08 UTC
