### ISSUE TITLE
index.ts files are not transpiling to init.lua

### ISSUE THREAD

**Issue by Validark** [roblox-ts/roblox-ts#291] opened 2019-03-22 10:29 UTC
According to the [documentation](https://roblox-ts.github.io/docs/usage/supported-features):
> Files named index.ts will be transpiled as init.lua in order to align with conventional syncing plugin details, allowing you to have scripts inside of other scripts in the game tree.

Problem:
![image](https://user-images.githubusercontent.com/15217173/54816828-50a56280-4c63-11e9-8a83-661547396932.png)

**Comment by evaera** [comment] 2019-03-25 22:43
Probable duplicate of #255

**Closed** 2019-06-03 16:54 UTC
Labels: bug
