### ISSUE TITLE
We should add iterators to Maps and Sets

### ISSUE THREAD

**Issue by Validark** [roblox-ts/roblox-ts#290] opened 2019-03-20 09:24 UTC
I don't care too much how it looks, but I am thinking something like the following:
```ts
const mySet = new Set<string>();

for (const str of mySet) {
	print(str);
}
// or
for (const str in mySet) {
	print(str);
}

const myMap = new Map<string, boolean>();

for (const [k, v] of myMap) {
}
```
To accomplish this, we can easily use simple type-dependant compilation [here](https://github.com/roblox-ts/roblox-ts/blob/master/src/transpiler/loop.ts#L221).

If anyone is completely at a loss, here is an example of how you could make the map iterator in the `es.d.ts` file
```ts
interface IteratorResult2<K, V> {
	done: boolean;
	value: [K, V];
}

interface Iterator2<K, V> {
	next(value?: any): IteratorResult2<K, V>;
	return?(value?: any): IteratorResult2<K, V>;
	throw?(e?: any): IteratorResult2<K, V>;
}
interface IterableIterator2<K, V> extends Iterator2<K, V> {
	[Symbol.iterator](): IterableIterator2<K, V>;
}

interface IteratorResult2<K, V> {
	done: boolean;
	value: [K, V];
}

interface Iterator2<K, V> {
	next(value?: any): IteratorResult2<K, V>;
	return?(value?: any): IteratorResult2<K, V>;
	throw?(e?: any): IteratorResult2<K, V>;
}
interface IterableIterator2<K, V> extends Iterator2<K, V> {
	[Symbol.iterator](): IterableIterator2<K, V>;
}

interface Map<K, V> {
	[Symbol.iterator](): IterableIterator2<K, V>;
}
```

I would love to hear people's opinions for how they think something like this could happen. I am pretty sure the example I gave with Maps is built-in to 2017 and later versions of TS

**Comment by evaera** [comment] 2019-03-20 17:38
Duplicate of #132

**Closed by evaera** 2019-03-20 17:38 UTC
Labels: duplicate
