### ISSUE TITLE
--rojo flag is not working while using watch mode

### ISSUE THREAD

**Issue by SpencerDevv** [roblox-ts/roblox-ts#2016] opened 2022-06-18 12:33 UTC
![image](https://user-images.githubusercontent.com/94411511/174437808-08ed6027-29c2-42d4-88b6-29ff2fe7cb9f.png)

As you can see here I am trying to use the --rojo flag here to use the lobby.project.json, but it uses the game.project.json.

My Filesystem:
![image](https://user-images.githubusercontent.com/94411511/174437836-5927cabe-e3a7-4e74-b19b-df3179227a3e.png)

**Comment by Dionysusnu** [comment] 2022-06-18 13:06
The only code path that will emit this warning is if the rojo setting isn't passed in the project options.. which means this is either an issue with your shell, with yargs, or the CLI wrapper. I've seen it before happening to someone else, not sure how they resolved it.

**Comment by Dionysusnu** [comment] 2022-06-18 19:20
I can't reproduce this locally, with the same command on the latest version of the compiler. Also on PowerShell on Windows 10, running indirectly via a npm script.

**Comment by joritochip** [comment] 2022-06-26 20:55
Seems like this is an issue with the flamework transformer, not roblox-ts. See https://github.com/rbxts-flamework/core/issues/53

**Comment by osyrisrblx** [comment] 2022-06-27 16:57
Closing this in favor of the flamework issue. I'm pretty certain that's what is causing this.

**Closed by osyrisrblx** 2022-06-27 16:57 UTC
Labels: bug
