### ISSUE TITLE
Ternaries should compile to if-then-else expressions

### ISSUE THREAD

**Issue by grilme99** [roblox-ts/roblox-ts#1684] opened 2021-11-01 19:49 UTC
With the release of the `if-then-else` expression in Luau, TypeScript ternary statements should compile to this.

https://devforum.roblox.com/t/luau-recap-october-2021/1531825

**Comment by Dionysusnu** [comment] 2021-11-01 19:49
Duplicate of #1674

**Closed** 2021-11-01 19:50 UTC
