### ISSUE TITLE
[Model] is not assignable to Model

### ISSUE THREAD

**Issue by Rhyrne** [roblox-ts/roblox-ts#282] opened 2019-03-16 23:06 UTC
When using this method:
`const character : Model = player.Character || player.CharacterAdded.Wait();`

It causes this error:
> Type 'Model | [Model]' is not assignable to type 'Model'.
  Type '[Model]' is missing the following properties from type 'Model': ClassName, GetBoundingBox, BreakJoints, GetExtentsSize, and 30 more.

evaera said this issue could be related to a recent LuaTuple change.

**Comment by Validark** [comment] 2019-03-23 10:17
Just wanted to follow up on the record:

This is the intended behavior. `Wait()` should return a LuaTuple of the proper arguments, which in this case is a Model. You should change your code to the following, as:
```ts
const character: Model = player.Character || player.CharacterAdded.Wait()[0];
```

Once https://github.com/roblox-ts/roblox-ts/pull/280 and https://github.com/roblox-ts/rbx-types/pull/46 are merged, the above code will transpile properly.

If people think that `Wait()` should sometimes return the single argument and sometimes return LuaTuples, we can have that debate, but I think it is best to have `Wait()` always return LuaTuples for consistency and ease.

If people really want us to change this, the easiest way would be to make a completely separate [RBXScriptSignal](https://github.com/roblox-ts/rbx-types/blob/master/include/roblox.d.ts#L28) interface, unless if someone wants to write a system for evaluating conditional LuaTuple types.

Demo of the easiest way:
```ts
// You would have to modify this to extract U[0]
// I am just leaving this the way it was though
type FunctionArgument<T> = T extends (...args: infer U) => void ? U : never;

interface RBXScriptSignalWithSingleArgument<T = Function, P = false> {
	Connect<O extends unknown[] = FunctionArgument<T>>(callback: P extends true ? FunctionArguments<T> extends unknown[] ? (...args: O) => void : T : T): RBXScriptConnection;
	Wait(): FunctionArgument<T>;
}
```
(you could probably eliminate P)

**Closed** 2019-03-23 23:49 UTC
Labels: bug
