### ISSUE TITLE
Assertion Failed! Destructuring not supported for type: any

### ISSUE THREAD

**Issue by rdot117** [roblox-ts/roblox-ts#2749] opened 2024-07-20 15:19 UTC
c:\local-documents-folder\github\untitled-ragdoll-sandbox\node_modules\roblox-ts\out\Project\functions\setupProjectWatchProgram.js:169
                throw e;
                ^

Error: Assertion Failed! Destructuring not supported for type: any
This is a compiler bug! Please submit a bug report here:
https://github.com/roblox-ts/roblox-ts/issues
    at assert (c:\local-documents-folder\github\untitled-ragdoll-sandbox\node_modules\roblox-ts\out\Shared\util\assert.js:7:15)
    at getAccessorForBindingType (c:\local-documents-folder\github\untitled-ragdoll-sandbox\node_modules\roblox-ts\out\TSTransformer\util\binding\getAccessorForBindingType.js:139:25)
    at transformArrayBindingPattern (c:\local-documents-folder\github\untitled-ragdoll-sandbox\node_modules\roblox-ts\out\TSTransformer\nodes\binding\transformArrayBindingPattern.js:19:80)
    at c:\local-documents-folder\github\untitled-ragdoll-sandbox\node_modules\roblox-ts\out\TSTransformer\nodes\binding\transformBindingName.js:21:81
    at TransformState.capturePrereqs (c:\local-documents-folder\github\untitled-ragdoll-sandbox\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:128:9)
    at transformBindingName (c:\local-documents-folder\github\untitled-ragdoll-sandbox\node_modules\roblox-ts\out\TSTransformer\nodes\binding\transformBindingName.js:19:62)
    at transformForInitializer (c:\local-documents-folder\github\untitled-ragdoll-sandbox\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformForOfStatement.js:67:64)
    at c:\local-documents-folder\github\untitled-ragdoll-sandbox\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformForOfStatement.js:92:39
    at c:\local-documents-folder\github\untitled-ragdoll-sandbox\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformForOfStatement.js:32:28
    at transformForOfStatement (c:\local-documents-folder\github\untitled-ragdoll-sandbox\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformForOfStatement.js:378:46)

**Comment by Dionysusnu** [comment] 2024-07-20 15:21
Duplicate of #2664. Not really a bug, just an ungraceful error. Roblox-ts generally does not support compiling code with `any` types.

**Closed** 2024-07-20 15:23 UTC
