### ISSUE TITLE
an bug

### ISSUE THREAD

**Issue by mamaue-master** [roblox-ts/roblox-ts#2599] opened 2024-01-29 17:28 UTC
the compiler terminal threw:

C:\Users\hanse\AppData\Roaming\npm\node_modules\roblox-ts\out\Project\functions\setupProjectWatchProgram.js:169
                throw e;
                ^

Error: Assertion Failed! 
This is a compiler bug! Please submit a bug report here:
https://github.com/roblox-ts/roblox-ts/issues
    at assert (C:\Users\hanse\AppData\Roaming\npm\node_modules\roblox-ts\out\Shared\util\assert.js:7:15)
    at createJsxAddChild (C:\Users\hanse\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\jsx\transformJsxChildren.js:159:25)
    at transformJsxChildren (C:\Users\hanse\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\jsx\transformJsxChildren.js:234:38)
    at transformJsxFragment (C:\Users\hanse\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\expressions\transformJsxFragment.js:19:53)
    at transformExpression (C:\Users\hanse\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\expressions\transformExpression.js:97:16)
    at C:\Users\hanse\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\jsx\transformJsxChildren.js:243:109
    at C:\Users\hanse\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:133:60
    at TransformState.capturePrereqs (C:\Users\hanse\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:128:9)
    at TransformState.capture (C:\Users\hanse\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:133:30)
    at transformJsxChildren (C:\Users\hanse\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\jsx\transformJsxChildren.js:243:49)

Node.js v18.17.1
Compiler exited with code 1

**Comment by Dionysusnu** [comment] 2024-01-29 18:25
Duplicate of #2252, #2139, and #2084. Check that all your JSX child expressions are valid elements.

**Comment by osyrisrblx** [comment] 2024-02-13 23:42
Closing as duplicate

**Closed by osyrisrblx** 2024-02-13 23:43 UTC
